Produce full downloads for each organization weekly
ivplus/aggregator pull request #98
Opened 2020-11-05 17:30 UTC by cbeer

Eventually, we might want to make this monthly, but for now run it frequently so we can see it in action more.

Fixes #95

2020-11-05 19:28 UTC, mejackreed requested changes
Quick request re: current storage constraints

2020-11-05 19:28 UTC, mejackreed commented on config/schedule.rb
> +  runner 'DownloadJob.enqueue_all'
Could we comment this out for now? Or what until we expand our storage and account for that?

2020-11-09 16:14 UTC, cbeer commented
I think this is ready for re-review now that we're compressing these dumps down to just a few GB per organization?

2020-11-09 16:57 UTC, mejackreed approved these changes

2020-11-09 16:57 UTC, merged